### ISSUE TITLE
Backup db using python and shell script

### ISSUE THREAD

**Issue by 13angs** [13angs/mysql-backup#1]
## Steps
- Freeze the lib

```bash
pip freeze > requirements.txt
```
- Running python input in docker

```bash
docker run -ti 13angs/mysql-backup:latest
```

```bash
docker run -i -v /home/bangz/develop/13/mysql-backup/data/backup:/usr/src/app/data/backup -v /var/run/docker.sock:/var/run/docker.sock 13angs/mysql-backup:latest
```

```bash
docker compose run mysql-backup
```

- Install deps

```bash
pip install -r requirements.txt
```

- backup command

```python
dump_cmd = f'docker exec -i {db_container_name} ' + \
        f'mysqldump -u {db_user} -p{db_pass} {db_name} ' + \
        f'> {backup_path}.sql'
```

- setting.json

```json
{
    "servers": [
        {
            "name": "eng-api-db",
            "port": 3306,
            "databases": [
                "EngCartService",
                "EngUserService"
            ]
        }
    ],
    "actions": [
        "backup",
        "restore"
    ],
    "dest": {
        "backup": "./data/backup",
        "restore": "./data/restore"
    }
}
```

- using mysql-client instead

dockerfile

```dockerfile
RUN apk update && \
    apk add mysql-client
```

devcon

```bash
sudo apt-get update && \
sudo apt-get install -y mariadb-client
```
- remove the `docker exec` python script
- Test using docker/docker-compose

```yml
version: '3.8'

services:
  mysql-backup:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: 13angs/mysql-backup:latest

    volumes:
      - type: bind
        source: ./data/backup
        target: /usr/src/app/data/backup

    networks:
      - eng-ssl-swarm-network

networks:
  eng-ssl-swarm-network:
    external: true
    name: eng-ssl-swarm-network
```

- check if deps exist or not

```sh
if command mysqldump --version >/dev/null 2>&1 ; then
    echo "mysqldump found"
    echo "version: $(mysqldump --version)"
else
    echo "mysqldump not found"
    echo "Installing required dependencies..."
    sudo apt-get update && \
    sudo apt-get install -y mariadb-client
fi
```

## Backup
- Select the action
- Select the server
- Select the database
- Multi select
- Create a folder each backup

multiple
```bash
server/multiple/date_time/databases.gz
```

single
```bash
server/single/service_name/date_time/database.gz
```

## Logging

```json
[
    {
        "server": "db_server",
        "database": "db_name",
        "created_date": "date_created",
        "status": "success",
        "action": "backup_or_restore",
        "dest": "path_where_the_file_is_located",
    }
]
```

- save to json file:
  - backup
  - restore 

## reference
-  https://stackoverflow.com/questions/40181344/how-to-annotate-types-of-multiple-return-values
- https://superuser.com/questions/1275519/how-do-i-create-a-mysql-client-docker-container-that-executes-a-mysql-script-aga
- https://stackoverflow.com/questions/57048428/e-package-mysql-client-has-no-installation-candidate-in-php-fpm-image-build-u
- https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose
- https://www.sqlshack.com/how-to-backup-and-restore-mysql-databases-using-the-mysqldump-command/
- https://stackoverflow.com/questions/33297857/how-to-check-dependency-in-bash-script
